server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          host: ${PROMTAIL_HOSTNAME}
          __path__: /var/log/*.log
      - targets: [localhost]
        labels:
          job: syslog
          host: ${PROMTAIL_HOSTNAME}
          __path__: /var/log/syslog
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: /(.+)
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - replacement: ${PROMTAIL_HOSTNAME}
        target_label: host
    pipeline_stages:
      - json:
          expressions:
            level: level
            event: event
            correlationId: correlationId
            tenantId: tenantId
            eventType: eventType
            contactId: contactId
            sessionId: sessionId
            visitorId: visitorId
      - labels:
          level:
          event:
          correlationId:
          tenantId:
          eventType:
          contactId:
          sessionId:
          visitorId:
